version: '3.4'

x-anchors:
  geth_config: &geth_config ./geth-config.json:/etc/geth-config.json
  aleth_config: &aleth_config ./aleth-config.json:/etc/aleth-config.json

  geth_node: &geth_node
    image: "ethereum/client-go:v1.8.17"
    command:
      - --bootnodes
      - enode://a20822d45dc080b7cf8398686be573bd5403c0c391eb42412f0640dd50eacb2eccb27d677beba265a8142bf086c1c1bf702ca7e6b6f75d18de9ab0b10e48809a@172.16.238.10:30301
      - --networkid
      - "8416"
      - --syncmode
      - "full"
    links:
      - bootnode

  aleth_node: &aleth_node
    build: ./aleth-instrumentation
    tty: true
    command:
      - --config
      - /etc/aleth-config.json
      - --network-id
      - "8416"
      - --peerset
      - required:a20822d45dc080b7cf8398686be573bd5403c0c391eb42412f0640dd50eacb2eccb27d677beba265a8142bf086c1c1bf702ca7e6b6f75d18de9ab0b10e48809a@172.16.238.10:30301
      - --no-bootstrap
      - -v
      - "4"
    links:
      - bootnode


services:
  bootnode:
    build: ./bootnode
    command:
      - -nodekey
      - /root/.ethereum/boot.key
      - -addr
      - 172.16.238.10:30301
    networks:
      app_net:
        ipv4_address: 172.16.238.10
    volumes:
      - ./data/bootnode:/root/.ethereum
      - ./data/bootnode:/root/logs/
    ports:
      - "30301:30301/udp"

  geth_node1:
    <<: *geth_node
    volumes:
      - *geth_config
      - ./data/geth_node1:/root/.ethereum
    networks:
      app_net:
        ipv4_address: 172.16.238.20

  geth_node2:
    <<: *geth_node
    volumes:
      - *geth_config
      - ./data/geth_node2:/root/.ethereum
    networks:
      app_net:
        ipv4_address: 172.16.238.21

  aleth_node1:
    <<: *aleth_node
    volumes:
      - *aleth_config
      - ./data/aleth_node1:/root/.ethereum
    networks:
      app_net:
        ipv4_address: 172.16.238.22

  aleth_node2:
    <<: *aleth_node
    volumes:
      - *aleth_config
      - ./data/aleth_node2:/root/.ethereum
    networks:
      app_net:
        ipv4_address: 172.16.238.23

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
