version: '3.4'

x-anchors:
  geth_config: &geth_config ./config/geth-config.json:/etc/geth-config.json
  aleth_config: &aleth_config ./config/aleth-config.json:/etc/aleth-config.json

  geth_node: &geth_node
    image: "ethereum/client-go:v1.8.17"
    command:
      - --bootnodes
      - enode://${BOOTNODE}
      - --networkid
      - "8416"
      - --syncmode
      - "full"
      - --miner.threads
      - "1"
    links:
      - bootnode

  aleth_node: &aleth_node
    build: ./aleth-instrumentation
    tty: true
    command:
      - --config
      - /etc/aleth-config.json
      - -t
      - "1"
      - --network-id
      - "8416"
      - --peerset
      - required:${BOOTNODE}
      - --no-bootstrap
    links:
      - bootnode


services:
  bootnode:
    build: ./bootnode
    command:
      - -nodekey
      - /root/.ethereum/boot.key
      - -addr
      - 172.16.238.10:30301
    networks:
      app_net:
        ipv4_address: 172.16.238.10
    volumes:
      - ./data/bootnode/ethereum:/root/.ethereum
      - ./data/bootnode/logs:/root/logs/
    ports:
      - "30301:30301/udp"

  geth_node1:
    <<: *geth_node
    volumes:
      - *geth_config
      - ./data/geth_node1/ethereum:/root/.ethereum
    networks:
      app_net:
        ipv4_address: 172.16.238.20

  geth_node2:
    <<: *geth_node
    volumes:
      - *geth_config
      - ./data/geth_node2/ethereum:/root/.ethereum
    networks:
      app_net:
        ipv4_address: 172.16.238.21

  aleth_node1:
    <<: *aleth_node
    volumes:
      - *aleth_config
      - ./data/aleth_node1/ethereum:/root/.ethereum
    networks:
      app_net:
        ipv4_address: 172.16.238.22

  aleth_node2:
    <<: *aleth_node
    volumes:
      - *aleth_config
      - ./data/aleth_node2/ethereum:/root/.ethereum
    networks:
      app_net:
        ipv4_address: 172.16.238.23

  instrumented_aleth_node1:
    <<: *aleth_node
    entrypoint:
      - valgrind
      - --log-file=/root/.ethereum/valgrind.log
      - --error-limit=no
      - /aleth/build/aleth/aleth
    volumes:
      - *aleth_config
      - ./data/instrumented_aleth_node1/ethereum:/root/.ethereum
      - ./data/instrumented_aleth_node1/build:/aleth/build
    networks:
      app_net:
        ipv4_address: 172.16.238.24


networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
