version: '3'
services:
  bootnode:
    build: ./bootnode
    command:
      - -nodekey
      - /root/.ethereum/boot.key
      - -addr
      - 172.16.238.10:30301
      - -verbosity
      - "9"
    networks:
      app_net:
        ipv4_address: 172.16.238.10
    volumes:
      - ./data/bootnode:/root/.ethereum
      - ./data/bootnode:/root/logs/
    ports:
      - "30301:30301/udp"

  geth_node:
    image: ethereum/client-go
    networks:
      app_net:
        ipv4_address: 172.16.238.11
    volumes:
      - ./geth-config.json:/etc/geth-config.json
      - ./data/geth_node:/root/.ethereum
    command:
      - --bootnodes
      - enode://a20822d45dc080b7cf8398686be573bd5403c0c391eb42412f0640dd50eacb2eccb27d677beba265a8142bf086c1c1bf702ca7e6b6f75d18de9ab0b10e48809a@172.16.238.10:30301
      - --networkid
      - "8416"
    links:
      - bootnode

  aleth_node:
    build: ./aleth-instrumentation
    networks:
      app_net:
        ipv4_address: 172.16.238.12
    tty: true
    command:
      - --config
      - /etc/aleth-config.json
      - --network-id
      - "8416"
      - --peerset
      - required:enode://a20822d45dc080b7cf8398686be573bd5403c0c391eb42412f0640dd50eacb2eccb27d677beba265a8142bf086c1c1bf702ca7e6b6f75d18de9ab0b10e48809a@172.16.238.10:30301
    volumes:
      - ./aleth-config.json:/etc/aleth-config.json
      - ./data/aleth_node:/root/.ethereum
    links:
      - bootnode

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
